### ISSUE TITLE
> I wrote a plugin based on bluwy's idea to implement it. https://github.com/jsonz1993/vite-plugin-load-css-module

### ISSUE THREAD

**Issue by jsonz1993** [jsonz1993/vite-plugin-load-css-module#3]
> I wrote a plugin based on bluwy's idea to implement it. https://github.com/jsonz1993/vite-plugin-load-css-module

It still load XX.module.less, and turn out to be 404 eror

_Originally posted by @lake2 in https://github.com/vitejs/vite/issues/6232#issuecomment-1043015451_

I released a version that I don't know if it can be reproduced now.

**Comment by lake2** [comment]
![image](https://user-images.githubusercontent.com/6293752/154708038-dd44f3a1-14c7-45d4-9377-d26cc92c5bf2.png)

我把你的项目下载到本地 npm build && cd playgroud/react && npx vite ./ 之后报错

**Comment by jsonz1993** [comment]
https://stackblitz.com/edit/vitejs-vite-tdpjax?file=src/App.tsx

我这边无法重现，不过代码思路的实现和vite的版本很强关联

**Comment by lake2** [comment]
> https://stackblitz.com/edit/vitejs-vite-tdpjax?file=src/App.tsx
> 
> 我这边无法重现，不过代码思路的实现和vite的版本很强关联

额 我用的最新版vite
