### ISSUE TITLE
404 when loading assets

### ISSUE THREAD

**Issue by X7Becka** [jsonz1993/vite-plugin-load-css-module#5]
Hello.
In example i'm getting 404 ERROR 
![chrome_hRcD0Do2sB](https://user-images.githubusercontent.com/51074290/155960555-83357e87-d7de-4ec6-a164-08b097e5eba4.png)
Also a few days yearly it worked correctly. What happened?

**Comment by jsonz1993** [comment]
If you are referring to the repository example, which I did not reproduce, try
  1. clean your working space and pull the latest code
  2. remove node_modules and re-install (project && playground)
  3. npm run build
  4. cd playground/react && npm run dev

Or clone project and perform 3, 4 of the above.



About 404 possible problem is vite version is not correct?
The implementation of the plugin is strictly dependent on the internal implementation of vite.
So for versioning my current idea is to use peerDependencies to correspond to different versions of vite.

> What happened?

You can see the details [here](https://github.com/jsonz1993/vite-plugin-load-css-module/pulls?q=is%3Apr+is%3Aclosed) .

**Comment by X7Becka** [comment]
As i can see, on macOS it works properly, but windows OS doesn't create .module.css files. Only *.css.
Which logs can help us with this problem?

**Comment by X7Becka** [comment]
Today i did on windows platform everything like yesterday on macOS and can confirm that .module.css files not creating. 
Looks like something wrong with write rights or difference between esbuild architecture.
And also i can confirm, problem could be in regex.

**Comment by X7Becka** [comment]
The problem with paths i guess 
![image](https://user-images.githubusercontent.com/51074290/156107753-f263fbcd-236f-49be-bb22-7ef25a57132b.png)

**Comment by jsonz1993** [comment]
> As i can see, on macOS it works properly, but windows OS doesn't create .module.css files. Only *.css. Which logs can help us with this problem?

I tested on the window virtual machine and found this problem.

**Comment by X7Becka** [comment]
Yay, thank you so much!
